# Generated by Django 4.2.3 on 2023-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_book_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default-cover.jpg', null=True, upload_to=''),
        ),
    ]
