# Generated by Django 4.2.3 on 2023-08-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default-cover.jpg', null=True, upload_to='uploads/'),
        ),
    ]
