# Generated by Django 4.2.3 on 2023-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(blank=True, default='15-06-2023', null=True),
        ),
    ]
