# Generated by Django 4.2.3 on 2023-08-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_book_author_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pagecount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
