# Generated by Django 4.2.3 on 2023-08-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_book_pagecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(default='2009-12-25', null=True),
        ),
    ]
